# Generated by Django 2.2.19 on 2023-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230208_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Ingredientrecipe', to='recipes.Ingredient'),
        ),
    ]
