# Generated by Django 2.2.19 on 2023-02-08 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230208_2240'),
        ('users', '0003_auto_20230204_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(related_name='user_favorite', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='user_shopping_cart', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
